### PR TITLE
Abel - Add Cat Shader

### PR DESCRIPTION
**Pull request by unoctium1**
Added a shadergraph for dealing with the UVs but still allowing for decent proceral changes. Should be decently performant and is currently pretty bare bones. Has a noise detail mask and allows for a fur texture but otherwise eyes, ears, and feet are just colors

### CODE REVIEW

**Comment by m4rtint** [comment]
image
Is this the noise your referring to

**Comment by unoctium1** [comment]
Yeah, I put the strength up pretty high just so its visible but it can be turned down in the material

**Comment by unoctium1** [comment]
The old cat models all also had noise detail maps so I figured I'd bring that over just for feature parity

**Review by m4rtint — CHANGES_REQUESTED** [review]
Can you place the CatPlaygroundSettings into its own folder? 
To separate each scenes different settings

**Review by m4rtint — APPROVED** [review]

**Comment by unoctium1** [comment]
I actually realized the orange cat in the scene has a broken prefab reference, so that screenshot is the old shader whoops. The orange cat prefabs looks similar though

**Pull request merged**
